[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
torch = "1.11.0"
torchvision = "0.12.0"
pandas = "^1.4.2"
scikit-learn = "^1.0"
tqdm = "^4.64.0"
gym = {version = "^0.23.1", extras = ["classic_control", "box2d"]}

[tool.poetry.dev-dependencies]
jupyterlab = "^3.3.4"
matplotlib = "^3.5.2"
black = "22.3.0"
ipywidgets = "^7.7.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
