[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]

[tool.poetry.dependencies]
python = "^3.8"
tensorflow = "2.5.1"
keras = "2.6.0"
pandas = "^1.3.2"
scikit-learn = "^0.24.2"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.1.9"
matplotlib = "^3.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
