[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
torch = "1.12.0"
torchvision = "0.13.0"
pandas = "^1.5.2"
scikit-learn = "^1.2"
tqdm = "^4.64.1"
gym = {version = "^0.26.2", extras = ["classic_control"]}

[tool.poetry.dev-dependencies]
jupyterlab = "^3.5.1"
matplotlib = "^3.6.2"
black = "22.10.0"
ipywidgets = "^8.0.3"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
