[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
torch = "1.12.0"
torchvision = "0.13.0"
pandas = "^1.4.4"
scikit-learn = "^1.1"
tqdm = "^4.64.1"
gym = {version = "^0.26.0", extras = ["classic_control", "box2d"]}

[tool.poetry.dev-dependencies]
jupyterlab = "^3.4.7"
matplotlib = "^3.6.0"
black = "22.8.0"
ipywidgets = "^8.0.2"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
