[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
torch = "1.10.2"
torchvision = "0.12.0"
pandas = "^1.4.0"
scikit-learn = "^1.0"
tqdm = "^4.63.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.3.2"
matplotlib = "^3.5.1"
black = "22.1.0"
ipywidgets = "^7.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
