name: dependabot-merge
on:
  pull_request:

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          command: merge --squash
          github-token: ${{ secrets.GITHUB_TOKEN }}
